name: example-environment
channels:
  - alubbock
  - conda-forge
  - https://repo.continuum.io/pkgs/free
  - defaults
dependencies:
  - alabaster>=0.7.8
  - aniso8601>=1.1.0
  - argcomplete>=0.8.1
  - astropy>=0.4.2
  - babel>=2.3.4
  - beautifulsoup4>=4.3.2
  - bitarray>=0.8.1
  - branca
  - dbf
  - descartes
  - folium
  - geopandas
  - geopy
  - ipywidgets
  - ipykernel
  - networkx
  - numpy
  - openpyxl
  - pandas
  - pyproj
  - requests
  - scikit-learn
  - scipy
  - selenium
  - shapely
  - tqdm
  - xlrd>=1.0.0
  - descartes
  - pip:
    - kml2geojson
    - gtfs_kit
    - backports-abc>=0.4
    - DateTime
    - tables>=3.4.2
    - pyPdf
    - simpledbf
    - backcall
    - geojson
